# Generated by Django 5.2.7 on 2025-11-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=100, unique=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
